### ISSUE TITLE
NullPointerException at MultiCompressDialog.java:44

### ISSUE THREAD

**Issue by imoblife** [openintents/filemanager#52]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.filemanager"
    android:installLocation="auto"
    android:versionCode="34"
    android:versionName="2.0.7" >

java.lang.NullPointerException
at com.filemanager.dialogs.MultiCompressDialog$1.compressFinished(MultiCompressDialog.java:44)
at com.filemanager.util.CompressManager$CompressTask.onCancelled(CompressManager.java:187)
at com.filemanager.util.CompressManager$CompressTask.onCancelled(CompressManager.java:1)
at android.os.AsyncTask.finish(AsyncTask.java:629)
at android.os.AsyncTask.access$600(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:213)
at android.app.ActivityThread.main(ActivityThread.java:4787)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
at dalvik.system.NativeStart.main(Native Method)

**Comment by friedger** [comment]
fixed by https://github.com/openintents/filemanager/commit/62c63409b48bc6a69e5bd12d6a97735cd1a121ca
